### PR TITLE
Use standard Guardian Prettier config

### PR DESCRIPTION
**Pull request by jamesmockett**
## What does this change?

We currently run Prettier against our code via a pre-commit hook, but as we don't have an explicit Prettier config we rely on the default settings. Small changes to files often result in the entire file being reformatted which makes diffs and PRs more difficult to review.

This adds the standard `@guardian/prettier` config (plus matching `.editorconfig` file) and runs Prettier against the entire codebase to apply consistent formatting. `eslint-config-prettier` is used to disable any ESLint rules that are duplicated by or conflict with Prettier.

## How to test

Whilst this PR doesn't include any functional changes it would be sensible to do some regression testing on key journeys as this touches much of the codebase.

### CODE REVIEW

**Comment by jamesmockett** [comment]
[Add explicit Prettier configuration](https://trello.com/c/rFaeFa4M/2893-add-explicit-prettier-configuration)

**Comment by vlbee** [comment]
Thank you!

**Review by rBangay — APPROVED** [review]
LGTM 👍 nice one

**Review by rBangay — APPROVED** [review]

**Review by rBangay — DISMISSED** [review]
Nice work 🎉

**Review by rBangay — APPROVED** [review]

**Pull request merged**
