### PR TITLE
Use Help Centre header as header for entire site

### PR DESCRIPTION
**Pull request by andrewHEguardian**
## What does this change?

Reuse the same header that uses the full 'The Guardian' logo across HelpCentre and Manage My Account. Slightly adjust it to have a smaller top margin as per product switching designs. 

## How to test

Visit MMA while signed in - see The Guardian logo on the right and My Account dropdown on the left. Visit `/help-centre` and see the same header. Sign out while on the help centre and see 'Sign In' on the left of the header.

Acceptance Criteria
- Roundel to be replaced with The Guardian logo
- The Guardian logo to hyperlink to The Guardian website
- 'My account' dropdown to be shifted to the left side on desktop, replacing the 'My Account' link, with dropdown functionality remaining the same as it currently is.

## Images

imageimage

## Accessibility

-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

### CODE REVIEW

**Comment by andrewHEguardian** [comment]
[MMA Header Changes](https://trello.com/c/eavDlFSe/3852-mma-header-changes)

**Review by charleycampbell — APPROVED** [review]
Looks good to me 🚀

**Review by jamesmockett — APPROVED** [review]
Looks good. Really nice to have the two headers consolidated into one 🚀

**Comment by andrewHEguardian** [comment]
Ran through the changes with Daniel B and he's happy

**Pull request merged**
