### PR TITLE
Post end-to-end testing minor spacing fixes

### PR DESCRIPTION
**Pull request by jamesmockett**
## What does this change?

Fixes a couple of minor issues noticed during end-to-end testing of the switching journey.

## Images

Screenshot 2023-02-10 at 16 49 17

Screenshot 2023-02-10 at 16 51 28

### CODE REVIEW

**Comment by jamesmockett** [comment]
[Product Switching: Post end-to-end testing fixes and updates](https://trello.com/c/2TgKFled/3872-product-switching-post-end-to-end-testing-fixes-and-updates)

**Comment by jamesmockett** [comment]
[Product Switching: End to End Test - Bug Fixes Placeholder](https://trello.com/c/3k7gJStC/3844-product-switching-end-to-end-test-bug-fixes-placeholder)

**Comment by jamesmockett** [comment]
[Product Switching: Spacing on Thank You page after full stop](https://trello.com/c/2r9cXgFU/3880-product-switching-spacing-on-thank-you-page-after-full-stop)

**Review by andrewHEguardian — APPROVED** [review]
👍 👾

**Pull request merged**
